# Generated by Django 2.2.2 on 2019-06-10 16:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_by', models.UUIDField(null=True)),
                ('edited_on', models.DateTimeField(null=True)),
                ('deleted_by', models.UUIDField(null=True)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(blank=True, max_length=140, null=True)),
                ('domain', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_by', models.UUIDField(null=True)),
                ('edited_on', models.DateTimeField(null=True)),
                ('deleted_by', models.UUIDField(null=True)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(blank=True, max_length=140, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
