# Generated by Django 2.2.5 on 2019-09-25 11:49

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190610_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_by', models.UUIDField(null=True)),
                ('edited_on', models.DateTimeField(null=True)),
                ('deleted_by', models.UUIDField(null=True)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('role_type', models.CharField(choices=[('SA', 'super_admin'), ('A', 'admin'), ('M', 'moderator'), ('U', 'user'), ('G', 'guest')], max_length=2, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
