# Generated by Django 2.1.7 on 2019-03-05 09:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 5, 9, 3, 53, 259513, tzinfo=utc)),
        ),
    ]
